/* DO NOT EDIT THIS FILE - it is machine generated */
#include "C:/Program Files/Java/jdk-17.0.2/include/jni.h"
/* Header for class net_purpleblob_metis_algo_metisalgoJNI */

#ifndef _Included_net_purpleblob_metis_algo_metisalgoJNI
#define _Included_net_purpleblob_metis_algo_metisalgoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_purpleblob_metis_algo_metisalgoJNI
 * Method:    METIS_OUTPUT_HASH_LENGTH_get
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_net_purpleblob_metis_algo_metisalgoJNI_METIS_1OUTPUT_1HASH_1LENGTH_1get
  (JNIEnv *, jclass);

/*
 * Class:     net_purpleblob_metis_algo_metisalgoJNI
 * Method:    metis_digest_mac_from_str
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_purpleblob_metis_algo_metisalgoJNI_metis_1digest_1mac_1from_1str
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_purpleblob_metis_algo_metisalgoJNI
 * Method:    metis_digest_mac_from_str_salt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_purpleblob_metis_algo_metisalgoJNI_metis_1digest_1mac_1from_1str_1salt
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     net_purpleblob_metis_algo_metisalgoJNI
 * Method:    metis_enable_printing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_purpleblob_metis_algo_metisalgoJNI_metis_1enable_1printing
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_purpleblob_metis_algo_metisalgoJNI
 * Method:    metis_is_device
 * Signature: (Ljava/lang/String;[Z)I
 */
JNIEXPORT jint JNICALL Java_net_purpleblob_metis_algo_metisalgoJNI_metis_1is_1device
  (JNIEnv *, jclass, jstring, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
