/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.purpleblob.metis.algo;

public class metisalgoJNI {
  public final static native short METIS_OUTPUT_HASH_LENGTH_get();
  public final static native int metis_digest_mac_from_str(String jarg1, String jarg2);
  public final static native int metis_digest_mac_from_str_salt(String jarg1, String jarg2, String jarg3);
  public final static native void metis_enable_printing(boolean jarg1);
  public final static native int metis_is_device(String jarg1, boolean[] jarg2);
}
