/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.purpleblob.metis.algo;

public class metisalgo {
  public static short getMETIS_OUTPUT_HASH_LENGTH() {
    return metisalgoJNI.METIS_OUTPUT_HASH_LENGTH_get();
  }

  public static metis_failure_reason metis_digest_mac_from_str(String mac_str, String out_buf) {
    return metis_failure_reason.swigToEnum(metisalgoJNI.metis_digest_mac_from_str(mac_str, out_buf));
  }

  public static metis_failure_reason metis_digest_mac_from_str_salt(String mac_str, String salt_str, String out_buf) {
    return metis_failure_reason.swigToEnum(metisalgoJNI.metis_digest_mac_from_str_salt(mac_str, salt_str, out_buf));
  }

  public static void metis_enable_printing(boolean enabled) {
    metisalgoJNI.metis_enable_printing(enabled);
  }

  public static metis_failure_reason metis_is_device(String mac_str, boolean[] out) {
    return metis_failure_reason.swigToEnum(metisalgoJNI.metis_is_device(mac_str, out));
  }

}
