/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.purpleblob.metis.algo;

public final class metis_failure_reason {
  public final static metis_failure_reason metis_failure_reason_none = new metis_failure_reason("metis_failure_reason_none");
  public final static metis_failure_reason metis_failure_reason_non_utf8_string_input = new metis_failure_reason("metis_failure_reason_non_utf8_string_input");
  public final static metis_failure_reason metis_failure_reason_input_format_error = new metis_failure_reason("metis_failure_reason_input_format_error");
  public final static metis_failure_reason metis_failure_reason_hex_range_error = new metis_failure_reason("metis_failure_reason_hex_range_error");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static metis_failure_reason swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + metis_failure_reason.class + " with value " + swigValue);
  }

  private metis_failure_reason(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private metis_failure_reason(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private metis_failure_reason(String swigName, metis_failure_reason swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static metis_failure_reason[] swigValues = { metis_failure_reason_none, metis_failure_reason_non_utf8_string_input, metis_failure_reason_input_format_error, metis_failure_reason_hex_range_error };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

